name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.19.1
  google_sign_in: 5.3.3
  firebase_auth: 3.4.1
  lottie: 1.3.0
  introduction_screen: 3.0.2
  avatar_glow: 2.0.2
  emoji_picker_flutter: ^1.3.0
  get_storage: 2.0.3
  cloud_firestore: 3.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

